@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package io.github.mrp_v2.coloredextradetails.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;